Koffein/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('coffees.urls')),
]

coffees/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'coffees'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('coffees/', views.CoffeeListView.as_view(), name='coffees'),
    path('orders/', views.OrderListView.as_view(), name='orders'),
    path('order/<int:pk>', views.OrderUserListView.as_view(), name='order_list'),
    path('order/<int:pk>/details', views.OrderDetailsView.as_view(), name='order_details'),
    path('new_order/', views.OrderCreate.as_view(), name='new_order'),
    path('update_order/<int:pk>', views.OrderUpdate.as_view(), name='update_order'),
    path('delete_order/<int:pk>', views.OrderDelete.as_view(), name='delete_order'),
    path('users/', views.UserListView.as_view(), name='users'),
    path('user/<int:pk>', views.UserOrderListView.as_view(), name='user_orders'),
    path('user/<int:pk>/<int:user_target>/details', views.UserOrderDetailsView.as_view(), name='user_order_details'),
    path('new_user/', views.UserCreate.as_view(), name='new_user_def'),
    path('new_user/<int:pk>', views.UserCreate.as_view(), name='new_user'),
    path('new_user/<int:pk>/coffees', views.UserUpdate.as_view(), name='new_user_coffees'),
    path('update_user/<int:pk>/<int:user_target>', views.CoffeeSelector.as_view(), name='select_coffee'),
    path('update_user/<int:pk>/<int:user_target>/checkout', views.UserUpdate.as_view(), name='update_user'),
    path('delete_user/<int:pk>/<int:user_target>', views.UserDelete.as_view(), name='delete_user'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='login.html'), name='logout'),
]

coffees/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Order(models.Model):
    closed = models.BooleanField(default=False)
    date = models.DateField()
    shipping = models.FloatField()

    def __str__(self):
        return str(self.date)


class Coffee(models.Model):
    name = models.CharField(max_length=200)
    price = models.FloatField()
    intensity = models.IntegerField()

    def __str__(self):
        return self.name


class CoffeeUserOrder(models.Model):
    paid = models.BooleanField(default=False)
    coffees = models.ManyToManyField(Coffee, through='CoffeeUserOrderQuantity')
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    order = models.ForeignKey(Order, on_delete=models.DO_NOTHING)

    class Meta:
        unique_together = ('user', 'order')

    def __str__(self):
        return self.user.username


class CoffeeUserOrderQuantity(models.Model):
    coffee = models.ForeignKey(Coffee, on_delete=models.CASCADE)
    cuo = models.ForeignKey(CoffeeUserOrder, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    class Meta:
        unique_together = ('coffee', 'cuo')

coffees/forms.py
from django import forms
from .models import Order, Coffee, CoffeeUserOrder, CoffeeUserOrderQuantity
from django.contrib.auth.models import User


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['date', 'shipping']
        labels = {
            'date': 'Fecha de cierre',
            'shipping': 'Portes'
        }
        widgets = {
            'date': forms.DateInput(attrs={'class': 'form-control', 'id': 'date', 'placeholder': 'dd/mm/yyyy'},
                                    format='%d/%m/%Y'),
            'shipping': forms.NumberInput(attrs={'class': 'form-control', 'id': 'shipping', 'placeholder': '00,00'})
        }


class OrderUpdateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['date', 'shipping', 'closed']
        labels = {
            'date': 'Fecha de cierre',
            'shipping': 'Portes',
            'closed': 'Cerrado'
        }
        widgets = {
            'date': forms.DateInput(attrs={'class': 'form-control', 'id': 'date', 'placeholder': 'dd/mm/yyyy'},
                                    format='%d/%m/%Y'),
            'shipping': forms.NumberInput(attrs={'class': 'form-control', 'id': 'shipping', 'placeholder': '00,00'}),
            'closed': forms.CheckboxInput(attrs={'class': 'form-control', 'id': 'closed'})
        }


class UserCreateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username']
        excluded = ['orders']
        labels = {
            'username': 'Nombre',
        }
        help_texts = {
            'username': ''
        }
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'id': 'name',
                                               'placeholder': 'nombre.apellido'}),
        }

    def post(self):
        return None


class CoffeeSelectorForm(forms.Form):
    def __init__(self, *args, **kwargs):
        order = Order.objects.get(id=kwargs.pop('order', None))
        user_target = User.objects.get(id=kwargs.pop('user_target', None))

        super(CoffeeSelectorForm, self).__init__(*args, **kwargs)

        coffee_list, created = CoffeeUserOrder.objects.get_or_create(order=order, user=user_target)

        for coffee in Coffee.objects.all():
            if coffee in coffee_list.coffees.all():
                checked = True
            else:
                checked = False
            self.fields['coffee_' + str(coffee.id)] = forms.BooleanField(required=False,
                                                                         label=coffee.name,
                                                                         widget=forms.CheckboxInput(
                                                                             attrs={'class': 'form-check-input',
                                                                                    'checked': checked}))


class UserUpdateForm(forms.Form):
    def __init__(self, *args, **kwargs):
        order = kwargs.pop('order', None)
        user = kwargs.pop('user_target', None)

        super(UserUpdateForm, self).__init__(*args, **kwargs)

        cuo = CoffeeUserOrder.objects.get(order=order, user=user)
        coffees = CoffeeUserOrderQuantity.objects.filter(cuo=cuo)

        for coffee in coffees:
            self.fields['coffee_' + str(coffee.coffee.id)] = forms.IntegerField(required=True,
                                                                                label=coffee.coffee.name,
                                                                                initial=coffee.quantity,
                                                                                widget=forms.NumberInput(
                                                                                    attrs={'class': 'form-check',
                                                                                           'placeholder': '=<1'}))

coffees/views.py
from django.db.models import Sum, F, FloatField, ExpressionWrapper
from django.shortcuts import redirect
from django.views import generic
from django.core import mail
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Coffee, Order, User, CoffeeUserOrder, CoffeeUserOrderQuantity
from coffees.forms import OrderCreateForm, OrderUpdateForm, UserCreateForm, UserUpdateForm, CoffeeSelectorForm


# Create your views here.
class IndexView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'base.html'
    login_url = '/login/'
    redirect_field_name = ''


class CoffeeListView(LoginRequiredMixin, generic.ListView):
    model = Coffee
    context_object_name = 'coffee_list'
    login_url = '/login/'


class OrderListView(LoginRequiredMixin, generic.ListView):
    model = Order
    context_object_name = 'order_list'
    login_url = '/login/'


class OrderUserListView(LoginRequiredMixin, generic.ListView):
    model = User
    template_name = 'coffees/order_user.html'
    context_object_name = 'user_list'
    login_url = '/login/'

    def get_queryset(self):
        order = self.kwargs['pk']
        return User.objects.filter(coffeeuserorder__order=order)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(OrderUserListView, self).get_context_data(**kwargs)
        context['order'] = self.kwargs['pk']
        context['closed'] = Order.objects.get(pk=self.kwargs['pk']).closed
        return context


class OrderDetailsView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'coffees/order_details.html'
    login_url = '/login/'

    def get_context_data(self, **kwargs):
        context = super(OrderDetailsView, self).get_context_data(**kwargs)
        order = Order.objects.get(pk=self.kwargs['pk'])
        try:
            cuo = CoffeeUserOrder.objects.filter(order=order)
            coffees = CoffeeUserOrderQuantity.objects.filter(
                cuo__in=cuo).values('coffee_id', 'coffee__name', 'coffee__price').annotate(
                quantity=Sum('quantity')).annotate(total=ExpressionWrapper(F('coffee__price') *
                                                                           F('quantity'), output_field=FloatField()))
            context['coffees'] = coffees
            total = 0
            for coffee in coffees:
                total += coffee['total']
            total += order.shipping
            context['shipping'] = order.shipping
            context['total'] = total
        except Exception as ex:
            return context

        return context


class OrderCreate(LoginRequiredMixin, generic.CreateView):
    model = Order
    form_class = OrderCreateForm
    success_url = '/orders'
    login_url = '/login/'


class OrderUpdate(LoginRequiredMixin, generic.UpdateView):
    model = Order
    form_class = OrderUpdateForm
    success_url = '/orders'
    login_url = '/login/'


class OrderDelete(LoginRequiredMixin, generic.DeleteView):
    model = Order
    success_url = '/orders'
    login_url = '/login/'


class UserListView(LoginRequiredMixin, generic.ListView):
    model = User
    template_name = 'coffees/user_list.html'

    def get_queryset(self):
        try:
            username = self.request.GET['username']
        except KeyError:
            username = ''

        if username != '':
            object_list = self.model.objects.filter(username__contains=username)
        else:
            object_list = self.model.objects.all()
        return object_list

    def get_context_data(self, **kwargs):
        context = super(UserListView, self).get_context_data(**kwargs)
        context['filter'] = self.request.GET.get('filter', '')
        return context


class UserOrderListView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'coffees/coffeeuserorder_list.html'
    login_url = '/login/'

    def get_context_data(self, **kwargs):
        context = super(UserOrderListView, self).get_context_data(**kwargs)
        user_target = kwargs['pk']
        try:
            cuo = CoffeeUserOrder.objects.filter(user=user_target).values('order__date', 'paid', 'order_id')

        except Exception as ex:
            return context

        context['orders'] = cuo
        context['user_target'] = user_target
        return context


class UserCreate(LoginRequiredMixin, generic.FormView):
    template_name = 'coffees/user_form.html'
    form_class = UserCreateForm
    login_url = '/login/'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(UserCreate, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        if 'pk' in self.kwargs:
            context['order'] = self.kwargs['pk']
        return context

    def get_success_url(self):
        return str(self.kwargs['pk']) + '/coffees'

    def post(self, request, *args, **kwargs):
        try:
            user = User.objects.get(username=request.POST['username'])
        except User.DoesNotExist:
            pw = User.objects.make_random_password()
            user = User.objects.create_user(username=request.POST['username'],
                                            email=request.POST['username'] + '@versia.com',
                                            password=pw)
            user.save()
            mail.send_mail('Koffein Service', 'Tu contraseña es ' + pw, 'asier.esteban@versia.com',
                           [request.POST['username'] + '@versia.com'])
        except Exception as ex:
            tr = ex

        if 'orders' in request.POST and request.POST['orders'] != '':
            order = Order.objects.get(id=int(request.POST['orders']))
        else:
            return redirect('/users/')
        try:
            CoffeeUserOrder.objects.get(order=order, user=user)
        except CoffeeUserOrder.DoesNotExist:
            cuo = CoffeeUserOrder(order=order, user=user)
            cuo.save()
        return redirect('/update_user/' + str(order.id) + '/' + str(user.id))


class CoffeeSelector(LoginRequiredMixin, generic.FormView):
    template_name = 'coffees/coffee_selector.html'
    form_class = CoffeeSelectorForm
    login_url = '/login/'

    def get_form_kwargs(self):
        kwargs = super(CoffeeSelector, self).get_form_kwargs()
        kwargs['user_target'] = self.kwargs['user_target']
        kwargs['order'] = self.kwargs['pk']
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(CoffeeSelector, self).get_context_data(**kwargs)
        context['user_target'] = self.kwargs['user_target']
        context['order'] = self.kwargs['pk']
        return context

    def post(self, request, *args, **kwargs):
        selected = []
        for i in request.POST:
            if i.startswith('coffee'):
                selected.append(int(i.split('_')[1]))

        order = Order.objects.get(id=kwargs['pk'])
        user_target = User.objects.get(id=kwargs['user_target'])
        try:
            cuo = CoffeeUserOrder.objects.get(order=order, user=user_target)
        except CoffeeUserOrder.DoesNotExist:
            cuo = CoffeeUserOrder(order=order, user=user_target)

        for coffee in selected:
            coffee_aux = Coffee.objects.get(pk=coffee)
            if coffee_aux not in cuo.coffees.all():
                cuoq = CoffeeUserOrderQuantity(coffee=coffee_aux, cuo=cuo)
                cuoq.save()

        coffees_remove = cuo.coffees.exclude(id__in=selected)

        for coffee in coffees_remove:
            c = CoffeeUserOrderQuantity.objects.get(coffee=coffee, cuo=cuo)
            c.delete()

        return redirect('/update_user/' + str(self.kwargs['pk']) + '/' + str(self.kwargs['user_target']) + '/checkout')


class UserUpdate(LoginRequiredMixin, generic.FormView):
    template_name = 'coffees/update_user.html'
    form_class = UserUpdateForm
    login_url = '/login/'

    def get_form_kwargs(self):
        kwargs = super(UserUpdate, self).get_form_kwargs()
        kwargs['user_target'] = self.kwargs['user_target']
        kwargs['order'] = self.kwargs['pk']
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(UserUpdate, self).get_context_data(**kwargs)
        context['user_target'] = self.kwargs['user_target']
        context['order'] = self.kwargs['pk']
        return context

    def post(self, request, *args, **kwargs):
        order = kwargs['pk']
        user_target = kwargs['user_target']
        coffees = []
        for data in request.POST:
            if data.startswith('coffee'):
                coffees.append({'key': int(data.split('_')[1]),  'quantity': int(request.POST[data])})
        try:
            cuo = CoffeeUserOrder.objects.get(order=order, user=user_target)
        except CoffeeUserOrder.DoesNotExist:
            return None

        if len(coffees) == 0:
            cuo.delete()
        else:
            for coffee in coffees:
                c_2 = CoffeeUserOrderQuantity.objects.get(coffee=coffee['key'], cuo=cuo)
                c_2.quantity = coffee['quantity']
                c_2.save()

        if request.user.is_staff:
            returner = '/order/' + str(order)
        else:
            returner = '/orders'
        return redirect(returner)


class UserDelete(LoginRequiredMixin, generic.DeleteView):
    model = CoffeeUserOrder
    login_url = '/login/'

    def get_success_url(self):
        return '/order/' + str(self.kwargs['pk'])

    def post(self, request, *args, **kwargs):
        order = kwargs['pk']
        user_target = kwargs['user_target']
        try:
            cuo = CoffeeUserOrder.objects.get(order=order, user=user_target)
        except CoffeeUserOrder.DoesNotExist:
            return None
        cuo.delete()
        return redirect(self.get_success_url())


class UserOrderDetailsView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'coffees/user_details.html'
    login_url = '/login/'

coffees/templates/coffees/coffee_list.html
{% extends 'base.html' %}

{% block content %}
<table class="table table-striped">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Nombre</th>
        <th scope="col">Intensidad [1-12]</th>
        <th scope="col">Precio</th>
    </tr>
    </thead>
    <tbody>
    {% for coffee in coffee_list %}
    <tr>
        <td>{{coffee.name}}</td>
        <td>{{coffee.intensity}}</td>
        <td>{{coffee.price}}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

coffees/templates/coffees/coffee_selector.html
{% extends 'base.html' %}

{% block content %}
<form method="post" action=" {% url 'coffees:select_coffee' order user_target %} ">{% csrf_token %}
    {% for field in form %}
    <div class="form-check">
        {{ field }}
        <label class="form-check-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
    </div>
    {% endfor %}
    <br>
    <button type="submit" class="btn btn-primary">Confirmar</button>
</form>
{% endblock %}

coffees/templates/coffees/coffees.html
{% extends 'coffees/menu.html' %}

{% block content %}
<table class="table table-striped">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Nombre</th>
        <th scope="col">Intensidad [1-12]</th>
        <th scope="col">Precio</th>
    </tr>
    </thead>
    <tbody>
    {% for coffee in coffee_list %}
    <tr>
        <td>{{coffee.name}}</td>
        <td>{{coffee.intensity}}</td>
        <td>{{coffee.price}}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

coffees/templates/coffees/coffeeuserorder_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="post">{% csrf_token %}
    <p>Seguro que quieres borrar "{{ object }}"?</p>
    <input class="btn btn-primary" role="button" type="submit" value="Confirmar" />
</form>
{% endblock %}

coffees/templates/coffees/coffeeuserorder_list.html
{% extends 'base.html' %}

{% block content %}
<table class="table table-striped">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Pedido</th>
        <th scope="col">Pagado</th>
        <th scope="col">Detalles</th>
    </tr>
    </thead>
    <tbody>
    {% for order in orders %}
    <tr>
        <td>{{order.order__date}}</td>
        <td>{% if order.paid %}Sí{% else %}No{% endif %}</td>
        <td>
            <a class="btn btn-dark" href="/user/{{order.order_id}}/{{user_target}}/details" role="button">Detalles</a>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

coffees/templates/coffees/order_details.html
{% extends 'base.html' %}

{% block content %}
<table class="table table-striped">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Café</th>
        <th scope="col">Cantidad</th>
        <th scope="col">Precio Unitario</th>
        <th scope="col">Precio Total</th>
    </tr>
    </thead>
    <tbody>
    {% for coffee in coffees %}
    <tr>
        <td>{{coffee.coffee__name}}</td>
        <td>{{coffee.quantity}}</td>
        <td>{{coffee.coffee__price}}</td>
        <td>{{coffee.total|floatformat:2}}€</td>
    </tr>
    {% endfor %}
    </tbody>
</table>

Portes del envio: {{shipping|floatformat:2}}€
<br>_____________________________________________<br>
Precio total del envio: {{total|floatformat:2}}€
<br><br>
<a class="btn btn-primary" href="/orders" role="button">Volver</a>
{% endblock %}

coffees/templates/coffees/order_form.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="post">{% csrf_token %}
    {{form.as_p}}
    <br>
    <input class="btn btn-primary" type="submit" value="Guardar" />
</form>
{% endblock %}

coffees/templates/coffees/order_list.html
{% extends 'base.html' %}

{% block content %}
{% if user.is_staff %}
<a class="btn btn-primary" href="/new_order/" role="button">Nuevo lote</a>
{% endif %}
<br><br>
<table class="table table-striped">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Fecha de cierre</th>
        <th scope="col">Portes</th>
        <th scope="col">Cerrado</th>
        {% if user.is_staff %}
        <th scope="col">Actualizar</th>
        {% else %}
        <th scope="col">Acciones</th>
        {% endif %}
    </tr>
    </thead>
    <tbody>
    {% for order in order_list %}
    <tr>
        <td>{{order.date}}</td>
        <td>{{order.shipping}}</td>
        <td>{% if order.closed %}Sí{% else %}No{% endif %}</td>
        {% if user.is_staff %}
        <td>
            {% if not order.closed %}
            <a class="btn btn-primary" href="/update_order/{{order.id}}" role="button">Editar</a>
            <a class="btn btn-danger" href="/delete_order/{{order.id}}" role="button">Eliminar</a>
            {% else %}
            <a class="btn btn-success" href="/order/{{order.id}}/details" role="button">Detalles</a>
            {% endif %}
            <a class="btn btn-dark" href="/order/{{order.id}}" role="button">Lista</a>
        </td>
        {% else %}
        <td>
            {% if not order.closed %}
            <a class="btn btn-dark" href="/update_user/{{order.id}}/{{user.id}}" role="button">Pedido</a>
            {% endif %}
        </td>
        {% endif %}
    </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}

coffees/templates/coffees/order_user.html
{% extends 'base.html' %}

{% block content %}
<a class="btn btn-primary" href="/new_user/{{order}}" role="button">Nuevo pedido</a>
<br><br>
<table class="table table-striped">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Usuario</th>
        <th scope="col">Pagado</th>
        <th scope="col">{% if not closed %}Actualizar {% else %} Detalles {% endif %}</th>
    </thead>
    <tbody>
    {% for user in user_list %}
    <tr>
        <td>{{user.username}}</td>
        <td>{% if user.paid %}Sí{% else %}No{% endif %}</td>
        <td>
            {% if not closed %}
            <a class="btn btn-primary" href="/update_user/{{order}}/{{user.id}}" role="button">Editar</a>
            <a class="btn btn-danger " href="/delete_user/{{order}}/{{user.id}}" role="button">Eliminar</a>
            {% else %}
            <a class="btn btn-success" href="/user/{{order}}/{{user.id}}/details" role="button">Detalles</a>
            {% endif %}
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
<br><br>
<a class="btn btn-primary" href="/orders" role="button">Volver</a>
{% endblock %}

coffees/templates/coffees/orders.html
{% extends 'coffees/menu.html' %}

{% block content %}
<a class="btn btn-primary" href="/new_batch/" role="button">Nuevo lote</a>
<br><br>
<table class="table table-striped">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Fecha de cierre</th>
        <th scope="col">Portes</th>
        <th scope="col">Cerrado</th>
        <th scope="col">Actualizar</th>
    </tr>
    </thead>
    <tbody>
    {% for order in order_list %}
    <tr>
        <td>{{order.date}}</td>
        <td>{{order.shipping}}</td>
        <td>{% if order.closed %}Sí{% else %}No{% endif %}</td>
        <td>
            <a class="btn btn-primary {% if order.closed %}disabled{% endif %}" href="{% if order.closed %}#{% else %}/update_batch/{{order.id}}{% endif %}" role="button">Editar</a>
            <a class="btn btn-danger {% if order.closed %}disabled{% endif %}" href="{% if order.closed %}#{% else %}/delete_batch/{{order.id}}{% endif %}" role="button">Eliminar</a>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

coffees/templates/coffees/update_user.html
{% extends 'base.html' %}

{% block content %}
<form method="post" action="{% url 'coffees:update_user' order user_target %}">{% csrf_token %}
    {{form.as_table}}
    <br>
    <button type="submit" class="btn btn-primary">Confirmar</button>
</form>
{% endblock %}

coffees/templates/coffees/user_details.html
{% extends 'base.html' %}

{% block content %}
<table class="table table-striped">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Café</th>
        <th scope="col">Cantidad</th>
        <th scope="col">Precio Unitario</th>
        <th scope="col">Precio Total</th>
    </tr>
    </thead>
    <tbody>
    {% for coffee in coffees %}
    <tr>
        <td>{{coffee.coffee__name}}</td>
        <td>{{coffee.quantity}}</td>
        <td>{{coffee.coffee__price}}</td>
        <td>{{coffee.total|floatformat:2}}€</td>
    </tr>
    {% endfor %}
    </tbody>
</table>

{% if closed %}
Portes del envio: {{shipping|floatformat:2}}€
<br>_____________________________________________<br>
Precio total del pedido: {{total|floatformat:2}}€
{% endif %}
<br><br>
{% if user.is_staff %}
    <a class="btn btn-primary" href="/order/{{order}}" role="button">Volver</a>
{% else %}
    <a class="btn btn-primary" href="/user/{{user.id}}" role="button">Volver</a>
{% endif %}
{% endblock %}

coffees/templates/coffees/user_form.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="post">{% csrf_token %}
    {{form.as_p}}
    <input hidden="hidden" name="orders" value="{{order}}">
    <br>
    <input class="btn btn-primary" type="submit" value="Siguiente" />
</form>
{% endblock %}

coffees/templates/coffees/user_list.html
{% extends 'base.html' %}

{% block content %}
<a class="btn btn-primary" href="/new_user/" role="button">Nuevo usuario</a>

<form style="float:right" class="form-inline" method="get" action="{% url 'coffees:users' %}">
    <div style="float:right" class="form-group mx-sm-3 mb-2 input-group">
        <input type="text" class="form-control" id="username" name="username" value="{{filter}}" placeholder="nombre de usuario">
        <div class="input-group-append">
            <span class="input-group-text" id="basic-addon2">@versia.com</span>
        </div>
    </div>
    <button type="submit" class="btn btn-primary mb-2">Buscar</button>
</form>

<table class="table table-striped">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Nombre</th>
        <th scope="col">Detalles</th>
    </tr>
    </thead>
    <tbody>
    {% for user in user_list %}
    {% if not user.is_staff%}
    <tr>
        <td>{{user.username}}</td>
        <td>
            <a class="btn btn-dark" href="/user/{{user.id}}" role="button">Lista</a>
        </td>
    </tr>
    {% endif %}
    {% endfor %}
    </tbody>
</table>

{% endblock %}